eureka:
    instance:
        hostname: 192.168.173.95
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8181
spring:
    application:
        name: account-server
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://116.62.62.26/seata-account
        password: 14789632
        username: root
logging:
  level:
    root: info
# -----------seata--------------
# -----------seata--------------
