eureka:
    instance:
        hostname: 192.168.173.95
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8180
spring:
    application:
        name: order-server
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://116.62.62.26/seata-order
        password: 14789632
        username: root
        type: com.alibaba.druid.pool.DruidDataSource

# -----------seata--------------
# 完整配置项参考：https://github.com/seata/seata/blob/1.1.0/script/client/spring/application.yml
seata:
    enabled: true
    application-id: applicationName
    tx-service-group: default
    enable-auto-data-source-proxy: true
    use-jdk-proxy: false
    client:
        rm:
            async-commit-buffer-limit: 1000
            report-retry-count: 5
            table-meta-check-enable: false
            report-success-enable: false
            lock:
                retry-interval: 10
                retry-times: 30
                retry-policy-branch-rollback-on-conflict: true
        tm:
            commit-retry-count: 5
            rollback-retry-count: 5
        undo:
            data-validation: true
            log-serialization: jackson
            log-table: undo_log
        log:
            exceptionRate: 100
    service:
        vgroup-mapping:
            default: fsp_tx # defaul是事务分组名称，fsp_tx是tc集群名称
        grouplist:
            default: 127.0.0.1:8091
        enable-degrade: false
        disable-global-transaction: false
    transport:
        shutdown:
            wait: 3
        thread-factory:
            boss-thread-prefix: NettyBoss
            worker-thread-prefix: NettyServerNIOWorker
            server-executor-thread-prefix: NettyServerBizHandler
            share-boss-worker: false
            client-selector-thread-prefix: NettyClientSelector
            client-selector-thread-size: 1
            client-worker-thread-prefix: NettyClientWorkerThread
            worker-thread-size: default
            boss-thread-size: 1
        type: TCP
        server: NIO
        heartbeat: true
        serialization: seata
        compressor: none
        enable-client-batch-send-request: true
    config:
        type: file
    registry:
        type: eureka
        eureka:
            application: fsp_tx
            weight: 1
            service-url: http://192.168.173.95:8761/eureka
